### PR TITLE
Fixed handling of subfield references in bulk insert

### LINKED ISSUE #32: bulkInsert removes undeclared subfields
If you have the following document definition:
```coffee
class Item extends Document
  @Meta
    name: 'Item'
    fields: =>
      foo:
        bar: @ReferenceField AnotherDocument, []
```

And you perform an `Item.documents.bulkInsert` operation on data like:
```coffee
[
  _id: "iBovvBKYBy89buvPC"
  hello: "world"
  foo:
    bar:
      _id: 'JkzTRmQpnR4Y7Qx8Q'
    fieldA: 1
    fieldB: "hello"      
]
```

Documents which will be inserted will not contain the fields `foo.fieldA` or `foo.fieldB`.

### PR DESCRIPTION
**Pull request by kostko**
Fixes #32

### CODE REVIEW

File: lib.coffee [hunk 1]
```diff
@@ -308,8 +308,18 @@ class globals.Document
...
       fieldsWalker @meta.fields
 
-      referencesIncludeProjection = LocalCollection._compileProjection referencesInclude
       referencesExcludeProjection = LocalCollection._compileProjection referencesExclude
+      referencesIncludeModification = (document) ->
+        # We can't use _compileProjection here as this would cause top-level fields to
+        # be overwritten when updating subfields.
+        result = {}
+        for path, value of referencesInclude
+          continue if value isnt 1
```
Comment (mitar) [inline lib.coffee]: Shouldn't all values be 1? Should this be an assert?

File: lib.coffee [hunk 2]
```diff
@@ -308,8 +308,18 @@ class globals.Document
...
+
+          value = _.reduce path.split('.'), ((doc, atom) -> doc[atom]), document
+          result[path] = value unless _.isUndefined value
```
Comment (mitar) [inline lib.coffee]: I don't think this `_.isUndefined value` is necessary, this are not fields from `observeChanges`? `undefined` will here be converted to `null` upon insertion. So if you would do normal insert with a document where field is `undefined`, would Meteor insert that field and make it `null`? If yes, then we should do it here as well.

Comment (mitar) [inline lib.coffee]: I would add here an assert that `result[path]` does not yet exist. Otherwise it might be overridden.

File: lib.coffee (hunk 1 above)
Comment (kostko) [inline lib.coffee]: No, above you have `referencesInclude = {_id: 0}`. But this should probably just be removed now.

Comment (mitar) [inline lib.coffee]: Aha, yes.

File: lib.coffee (hunk 2 above)
Comment (kostko) [inline lib.coffee]: Without the `_.isUndefined value` check I get the following errors from PeerDB while inserting documents which don't contain the defined fields specified as an array of references:
```
Document 'Foo' 'yjJ4AAyrFhDgWupgL' field 'something' was updated with a non-array value: null
```

In this case, the proper solution would be to set the field to `[]` instead of `null`?

Comment (mitar) [inline lib.coffee]: Where you have this? In tests? I see that we do not have tests for reference fields inside arrays currently?

Comment (kostko) [inline lib.coffee]: No, this is in another project which uses PeerDB ;-)

I will add tests.

Comment (kostko) [inline lib.coffee]: > I would add here an assert that result[path] does not yet exist. Otherwise it might be overridden.

It can't exist as we are iterating over keys of a dictionary, which are always unique? So no path will be used twice.

Comment (mitar) [inline lib.coffee]: True.

Comment (mitar) [inline lib.coffee]: > In this case, the proper solution would be to set the field to [] instead of null?

Or simply omit the field. Not trying to set it to `null` at all. But yea, we can also be explicit. The point is, if source document didn't contain an optional field (author does not want to even set it), with current code it seems we force it to `null`, no? So I would agree that optional reference fields should be `null` in the first pass, but only if they really exist and will be set in the second pass. If the do not exist at all in the first pass, they should not be set by our code.
